CREATE TABLE [dbo].[QuestionSetQuestion]
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),

	QuestionSetSection UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [QuestionSetSection](Id),
	QuestionSet UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [QuestionSet](Id),
	Question UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Question](Id),

	QuestionOrder INTEGER NOT NULL,
	ShowOnQuestionsPage BIT NOT NULL,
	IsOptional BIT NOT NULL,

	FrontingQuestion UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES [Question](Id)
)
