CREATE TABLE [dbo].[AnswerPartResponse]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),

	[AnswerPart] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [AnswerPart](Id),
	[OrderWithinAnswerPart] INTEGER NOT NULL
)
