using Agrimetrics.DataShare.Api.Logic.ModelData.DataShareRequests.QuestionStatusDeterminations;

namespace Agrimetrics.DataShare.Api.Logic.Services.AcquirerDataShareRequest.DataShareRequestQuestionStatusesDeterminations;

internal class DataShareRequestQuestionSetCompletenessDeterminationResult : IDataShareRequestQuestionSetCompletenessDeterminationResult
{
    public required IEnumerable<IDataShareRequestQuestionSetQuestionStatusDataModel> QuestionsRequiringAResponse { get; init; }
}