CREATE TABLE [dbo].[QuestionFooter]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),

	[Question] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Question](Id),

	[Header] NVARCHAR(128) NULL
)
