CREATE TABLE [dbo].[Submission]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),

	[DataShareRequest] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[DataShareRequest],
	[Notes] NVARCHAR(MAX) NOT NULL DEFAULT ''
)
